import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Complete your look with our trendy cap for boys, combining style and comfort.",
},
{
    _id: 1002,
    img: spfTwo,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Add elegance to your living room with our stylish gray tea table, perfect for entertaining guests.",
},
{
    _id: 1003,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Enjoy high-quality sound with these comfortable and durable headphones, perfect for music lovers.",
},
{
    _id: 1004,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Protect your eyes in style with our sleek black sunglasses, offering both UV protection and modern design.",
},
{
    _id: 1005,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Bring a fresh touch to your space with our elegant flower base, designed to complement any décor.",
},
{
    _id: 1006,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "Stay organized and stylish with our new gray backpack, perfect for daily use and travel.",
},
{
    _id: 1007,
    img: bestSellerThree,
    productName: "Household materials",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Organize your home with our affordable and practical household materials, designed for everyday use.",
},
{
    _id: 1008,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "Travel in comfort with our spacious and durable black travel bag, perfect for all your adventures.",
},
{
    _id: 1009,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Add a touch of elegance to your home with our round table clock, designed to suit any interior.",
},
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Explore the latest technology with our sleek and modern smart watch, offering advanced features and comfort.",
},
{
    _id: 1011,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Organize your space in style with our versatile and durable cloth basket, perfect for any room.",
},
{
    _id: 1012,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Delight your little one with these colorful and engaging toys, designed for fun and development.",
},
{
    _id: 1013,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Bring joy to your baby's playtime with these safe, cheerful, and interactive toys.",
},
{
    _id: 1014,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Stay connected and track your health with our high-tech smart watch, designed for the modern lifestyle.",
},
{
    _id: 1015,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "A playful and educational addition to your baby's toy collection, crafted with care and creativity.",
},
{
    _id: 1016,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Embrace the future with our stylish smart watch, packed with features to enhance your daily life.",
},
{
    _id: 1017,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "Travel in comfort and style with our durable and spacious travel bag, perfect for all your adventures.",
},
{
    _id: 1018,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Add elegance to your home with our round table clock, designed to complement any interior decor.",
},
{
    _id: 1019,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "The ultimate smart watch experience, combining functionality with a sleek, modern design.",
},
{
    _id: 1020,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Store your essentials in a practical and stylish way with our multi-purpose cloth basket.",
},
{
    _id: 1021,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Experience immersive sound with our comfortable and high-quality headphones, perfect for music lovers.",
},
{
    _id: 1022,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Protect your eyes in style with our premium sunglasses, offering both UV protection and modern fashion.",
},
{
    _id: 1023,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Bring a touch of nature to your space with our elegant flower base, perfect for fresh blooms.",
},
    {
      _id: 1024,
      img: spfOne,
      productName: "Cap for Boys",
      price: "35.00",
      color: "Blank and White",
      badge: true,
      des: "This cap is perfect for boys who love to stay stylish and cool. It provides comfort and protection from the sun."
    },
    {
      _id: 1025,
      img: spfTwo,
      productName: "Tea Table",
      price: "180.00",
      color: "Gray",
      badge: true,
      des: "A sleek and modern tea table to complement your living room decor, providing a stylish and practical centerpiece."
    },
    {
      _id: 1026,
      img: spfThree,
      productName: "Headphones",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Enjoy superior sound quality and comfort with these headphones, designed for both music lovers and casual listeners."
    },
    {
      _id: 1027,
      img: spfFour,
      productName: "Sun glasses",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "These sunglasses provide optimal protection from harmful UV rays, all while adding a stylish touch to your outfit."
    },
    {
      _id: 1028,
      img: bestSellerOne,
      productName: "Flower Base",
      price: "35.00",
      color: "Blank and White",
      badge: true,
      des: "This elegant flower base adds a touch of nature to any room, perfect for displaying your favorite flowers or plants."
    },
    {
      _id: 1029,
      img: bestSellerTwo,
      productName: "New Backpack",
      price: "180.00",
      color: "Gray",
      badge: false,
      des: "A versatile and durable backpack designed for comfort, perfect for daily use or travel with ample storage space."
    },
    {
      _id: 1030,
      img: bestSellerThree,
      productName: "Household materials",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "A collection of essential household materials that are both functional and convenient for everyday use."
    },
    {
      _id: 1031,
      img: bestSellerFour,
      productName: "Travel Bag",
      price: "220.00",
      color: "Black",
      badge: false,
      des: "A spacious and durable travel bag, perfect for long trips or weekend getaways, designed for easy packing and comfort."
    },
    {
      _id: 1032,
      img: newArrOne,
      productName: "Round Table Clock",
      price: "44.00",
      color: "Black",
      badge: true,
      des: "This round table clock is a stylish addition to any space, offering both a unique design and reliable functionality."
    },
    {
      _id: 1033,
      img: newArrTwo,
      productName: "Smart Watch",
      price: "250.00",
      color: "Black",
      badge: true,
      des: "A cutting-edge smart watch that keeps you connected, tracks your fitness goals, and monitors your health in real-time."
    },
    {
      _id: 1034,
      img: newArrThree,
      productName: "Cloth Basket",
      price: "80.00",
      color: "Mixed",
      badge: true,
      des: "This cloth basket is perfect for organizing your laundry or storing household items with its spacious and eco-friendly design."
    },
    {
      _id: 1035,
      img: newArrFour,
      productName: "Funny toys for babies",
      price: "60.00",
      color: "Mixed",
      badge: false,
      des: "Entertain your little one with these fun and safe toys, designed to encourage learning and play."
    },
    {
      _id: 1036,
      img: newArrTwo,
      productName: "Funny toys for babies",
      price: "60.00",
      color: "Mixed",
      badge: false,
      des: "These playful toys are sure to make your baby smile, offering a fun and engaging experience."
    },
    {
      _id: 1037,
      img: newArrFour,
      productName: "Funny toys for babies",
      price: "60.00",
      color: "Mixed",
      badge: false,
      des: "Colorful and entertaining toys for babies that promote early development through playful interaction."
    },
    {
      _id: 1038,
      img: newArrTwo,
      productName: "Smart Watch",
      price: "250.00",
      color: "Black",
      badge: true,
      des: "Monitor your fitness, track your goals, and stay connected with this smart watch, perfect for an active lifestyle."
    },
    {
      _id: 1039,
      img: bestSellerFour,
      productName: "Travel Bag",
      price: "220.00",
      color: "Black",
      badge: false,
      des: "Travel in style with this practical and spacious travel bag, perfect for carrying all your essentials on the go."
    },
    {
      _id: 1040,
      img: newArrOne,
      productName: "Round Table Clock",
      price: "44.00",
      color: "Black",
      badge: true,
      des: "A sleek, round clock that blends seamlessly with any decor, offering both aesthetic appeal and accurate timekeeping."
    },
    {
      _id: 1041,
      img: newArrTwo,
      productName: "Smart Watch",
      price: "250.00",
      color: "Black",
      badge: true,
      des: "A smart watch designed for functionality and style, with features that support fitness tracking and communication."
    },
    {
      _id: 1042,
      img: newArrThree,
      productName: "Cloth Basket",
      price: "80.00",
      color: "Mixed",
      badge: true,
      des: "Organize your home with this cloth basket, designed to store and sort your laundry or other household items efficiently."
    },
    {
      _id: 1043,
      img: spfThree,
      productName: "Headphones",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "High-quality headphones that deliver clear sound and deep bass, perfect for listening to your favorite music anytime."
    },
    {
      _id: 1044,
      img: spfFour,
      productName: "Sun glasses",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Keep your eyes safe from the sun while looking stylish with these high-quality sunglasses that fit any occasion."
    },
    {
      _id: 1045,
      img: bestSellerOne,
      productName: "Flower Base",
      price: "35.00",
      color: "Blank and White",
      badge: true,
      des: "A minimalist flower base that enhances any space, perfect for fresh flowers or decorative greenery."
    },
    {
      _id: 1046,
      img: spfOne,
      productName: "Cap for Boys",
      price: "35.00",
      color: "Blank and White",
      badge: true,
      des: "A trendy cap for boys, offering both style and comfort for everyday wear."
    }
  ];
  
// =================== PaginationItems End here =================
